version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "5173:5173"  # Porta padrão do Vite
    volumes:
      - .:/app
      - /app/node_modules  # Evita sobrescrever node_modules do container
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  # Para hot reload no Docker
    stdin_open: true
    tty: true